### ISSUE TITLE
Using a deprecated function of Pandas in experiment jupyter notebook

### ISSUE THREAD

**Issue by MrP29** [hamzehkhazaei/EECS4222_Project_1#2]
**Error Message**
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_80255/2976911277.py in ?()
      7 
      8     if results is None:
      9         results = df_result
     10     else:
---> 11         results = results.append(df_result)
     12 
     13 results, filename = lt.prepare_results_from_df(results)

~/miniconda/lib/python3.11/site-packages/pandas/core/generic.py in ?(self, name)
   6289             and name not in self._accessors
   6290             and self._info_axis._can_hold_identifiers_and_holds_name(name)
   6291         ):
   6292             return self[name]
-> 6293         return object.__getattribute__(self, name)

AttributeError: 'DataFrame' object has no attribute 'append'
```

**Reason of Error**
Below code is a snippet of Experiment With/Without HPA part in ```/notebooks/experiment.ipynb``` file
```
# create a folder for results
!mkdir -p results
# parse the results
results = None
for result in arr_results:
    df_result = pd.DataFrame(data=result)
    
    if results is None:
        results = df_result
    else:
        results = results.append(df_result)                    <-------- line of error

results, filename = lt.prepare_results_from_df(results)
# get a list of columns
results.columns
```
In the for loop, currently using ```append()``` method to change data type from list to pandas dataframe.
However, the ```append()``` method is **deprecated** since version 1.4.0 (https://pandas.pydata.org/pandas-docs/version/1.4/reference/api/pandas.DataFrame.append.html)
And it may cause an error depending on version of pandas

**Possible Solution**
use ```concat()``` method instead of append.
(https://pandas.pydata.org/pandas-docs/version/1.4/reference/api/pandas.concat.html#pandas.concat)

e.g.) ```results = pd.concat([results, df_result], ignore_index=True)```

**Comment by 2arian3** [comment]
Hi @MrP29,
Thank you for bringing this problem to our attention.
